name: NetworkBoosters
version: '${version}'

main: com.stephanofer.networkBoosters.NetworkBoosters
bootstrapper: com.stephanofer.networkBoosters.NetworkBoostersBootstrap
loader: com.stephanofer.networkBoosters.NetworkBoostersLoader
api-version: '26.2'
load: POSTWORLD

authors: [ stephanofer ]
website: stephanofer.com
